name: beatsleuth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  http: ^0.13.4
  logging: ^1.1.1
  equatable: ^2.0.0
  just_audio: ^0.9.32
  audio_session: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CircularStd
      fonts:
        - asset: build/flutter_assets/fonts/CircularStd/CircularStd-Black.ttf
          weight: 900
        - asset: build/flutter_assets/fonts/CircularStd/CircularStd-Bold.ttf
          weight: 700
        - asset: build/flutter_assets/fonts/CircularStd/CircularStd-Book.ttf
          weight: 400
        - asset: build/flutter_assets/fonts/CircularStd/CircularStd-Medium.ttf
          weight: 500
