name: beatsleuth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  http: ^0.13.4
  logging: ^1.1.1
  equatable: ^2.0.0
  url_launcher: ^6.1.11
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.2
  wave: ^0.2.2
  page_transition: ^2.0.9
  cloud_firestore: ^4.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoSinFondov2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 900
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
