// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WWgrsq2DKrVTcUSKOXCgt__k_3zTRYQ',
    appId: '1:386644677721:web:7675f82d47881907000d48',
    messagingSenderId: '386644677721',
    projectId: 'beatsleuth-b222f',
    authDomain: 'beatsleuth-b222f.firebaseapp.com',
    storageBucket: 'beatsleuth-b222f.appspot.com',
    measurementId: 'G-FB4CS9TG81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5_C5JkuIcKe6CqpacSY55rssx2PKX24',
    appId: '1:386644677721:android:289686c32cc48399000d48',
    messagingSenderId: '386644677721',
    projectId: 'beatsleuth-b222f',
    storageBucket: 'beatsleuth-b222f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lm81GJfi6mgfE4n6SzX8I5DG2ZxrfPs',
    appId: '1:386644677721:ios:e32390f3407e2361000d48',
    messagingSenderId: '386644677721',
    projectId: 'beatsleuth-b222f',
    storageBucket: 'beatsleuth-b222f.appspot.com',
    iosBundleId: 'com.example.beatsleuth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_lm81GJfi6mgfE4n6SzX8I5DG2ZxrfPs',
    appId: '1:386644677721:ios:ea82f3fb93f90a37000d48',
    messagingSenderId: '386644677721',
    projectId: 'beatsleuth-b222f',
    storageBucket: 'beatsleuth-b222f.appspot.com',
    iosBundleId: 'com.example.beatsleuth2.RunnerTests',
  );
}
